Add seeding status
Purfview/IMDb-Scout-Mod pull request #238
Opened 2024-11-05 08:40 UTC by Audionut

https://ptpimg.me/ydjdp5.png

Before I get too caried away with this, what say thee.
Icon color is just standout, I'll defer to any suggestion.

Obviously not every site would be supported.

2024-11-05 12:44 UTC, Purfview commented
Interesting idea.

>Obviously not every site would be supported.

Why not? I guess you mean that for this to work you need `positiveMatch`? Maybe `positiveMatch2` could be introduced?

2024-11-05 13:12 UTC, Audionut commented
From experience with that sites script I maintain, not every site returns seeding status, either/or HTML or API.

The only thing I've done so far is see if I could actually make it work. I have done exactly zero testing save for that screenshot output. Although, I did have icons on one line first, and the seeded icon was first. Not sure if that was because of the order list, or because it's else if before else 'found'.

Presumably I could make it an option. I'm on mobile now, but presumably I could add an option check before the else if and assign icon as a seeding match.

2024-11-05 13:29 UTC, Purfview commented
>From experience with that sites script I maintain, not every site returns seeding status, either/or HTML or API.

That I understand, I thought that you meant it returns status but it wouldn't be supported.

>I did have icons on one line first, and the seeded icon was first..

That depends from order in `const valid_states`.

>Presumably I could make it an option. I'm on mobile now, but presumably I could add an option check before the else if and assign icon as a seeding match.

Make a post there, if noone complains then no need for option, I think.

2024-11-07 09:43 UTC, Audionut commented
Apart from waiting for that feedback, I don't think I can do much more with this. No other site I have access too has a seeding element available to hook onto.

If this gets pushed, would you like me to create an issue outlining how to find and add the regex match?

2024-11-07 09:56 UTC, Purfview commented
>If this gets pushed, would you like me to create an issue outlining how to find and add the regex match?

Eventually it will be, yeah you can create it [at show and tell](https://github.com/Purfview/IMDb-Scout-Mod/discussions/categories/show-and-tell) discussion, I'll link it in the PR "guide".

2024-11-07 10:34 UTC, Purfview commented
> I don't think I can do much more with this.

There is still one pending review.

2024-11-07 21:39 UTC, Audionut commented
> There is still one pending review.

I don't see a review anywhere.

2024-11-07 22:36 UTC, Audionut commented
Nope. If you do actually mean a review comment on some line/s of code, it does have to be confirmed, I think top right hand corner, after making a comment at a line of code. It's a bit clunky how that works.

2024-11-07 22:40 UTC, Purfview commented
Can you make a screenshot what is there for you?

2024-11-07 23:12 UTC, Audionut commented
https://ptpimg.me/7lz2ru.png

2024-11-07 23:15 UTC, Purfview requested changes

2024-11-07 23:17 UTC, Purfview commented
Did it appeared now?

2024-11-07 23:25 UTC, Audionut commented on IMDb_Scout_Mod.user.js
> +                                                                            : icon.css('border-color', 'rgb(130,0,130)');
Something like this?

2024-11-07 23:30 UTC, Purfview commented on IMDb_Scout_Mod.user.js
> +                                                                            : icon.css('border-color', 'rgb(130,0,130)');
Yeah

2024-11-08 04:56 UTC, Audionut commented
> Eventually it will be, yeah you can create it at [show and tell](https://github.com/Purfview/IMDb-Scout-Mod/discussions/categories/show-and-tell) discussion, I'll link it in the PR "guide".

Added: https://github.com/Purfview/IMDb-Scout-Mod/discussions/240

I'll correct the link after merge so I can delete the branch.

2024-11-24 15:56 UTC, merged